Train:
  batch_size: 3
  learning_rate: 0.02
  reg: 0.0001
  epochs: 15
  steps: [13, 14]
  warmup: 0
  momentum: 0.9

network:
  model: SimpleRNN # TwoLayerNet or VanillaCNN or MyModel or ResNet-32

input:
  data: ../data/dataset/600.perlbench_s-210B.champsimtrace.dat 
  label: ../data/dataset/600.perlbench_s-210B.champsimtrace.lab 


loss:
  loss_type: CE # CE or Focal