
# general setting for both train and validation
General: 
  epochs: 10
  shuffle: False # shuffle data or not
  # model config
  model: "SimSeq"
  save_best: True # save the best model during training
  # loss config
  loss_type: CE # NLL, CE or Focal
  reweight: False  # True with Focal Loss

# setting for training  
Train: 
  tra_batch_size: 64
  learning_rate: 0.01
  reg: 0.0001
  clip:  0.5 # clip threshold
  # taining set
  # train_data: ../data/dataset/train/600.perlbench_s-210B.champsimtrace.dat 
  # train_label: ../data/dataset/train/600.perlbench_s-210B.champsimtrace.lab 
  train_data: ../data/dataset/train/641.leela_s-800B.champsimtrace.dat 
  train_label: ../data/dataset/train/641.leela_s-800B.champsimtrace.lab 

# setting for validation
Validate:
  val_batch_size: 128
  # validation set
  valid_data: ../data/dataset/validate/641.leela_s-800B.champsimtrace.dat 
  valid_label: ../data/dataset/validate/641.leela_s-800B.champsimtrace.lab     

# pre-trained model for testing
Pre-trained:
  pt_path: checkpoints/simseq.pth # path to pre-train model
