Train:
  batch_size: 32
  learning_rate: 0.02
  reg: 0.0001
  epochs: 5
  clip:  0.5 # clip threshold

network:
  model: "SimSeq"
  save_best: True

input:
  data: ../data/dataset/600.perlbench_s-210B.champsimtrace.dat 
  label: ../data/dataset/600.perlbench_s-210B.champsimtrace.lab 
  shuffle: False

loss:
  loss_type: CE # NLL, CE or Focal
  reweight: False  # True with Focal Loss